name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint black flake8
          
      - name: Check code formatting with Black
        run: |
          echo "Checking code formatting..."
          black --check --diff . || echo "Code formatting issues found (non-blocking)"
          
      - name: Run Flake8 linting
        run: |
          echo "Running Flake8 linting..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || echo "Linting issues found (non-blocking)"
          
      - name: Validate project structure
        run: |
          echo "✅ Validating project structure..."
          ls -la
          echo "✅ Project structure validation completed"
