name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Explicit permissions for security
permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pylint mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Check code formatting with Black
        run: |
          black --check --diff . || echo "Code formatting issues found"
          
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics || true
          
      - name: Lint with pylint
        run: |
          pylint **/*.py --errors-only || true
          
      - name: Type checking with mypy
        run: |
          mypy . --ignore-missing-imports || true
          
      - name: Check project structure
        run: |
          echo "✅ Checking project structure..."
          if [ -f "requirements.txt" ]; then echo "✅ requirements.txt found"; fi
          if [ -f "README.md" ]; then echo "✅ README.md found"; fi
          if [ -f ".gitignore" ]; then echo "✅ .gitignore found"; fi
          if [ -d ".github/workflows" ]; then echo "✅ GitHub workflows found"; fi
          echo "✅ Project structure validation completed"
